### ISSUE TITLE
Индекс документации это список блоков

### ISSUE THREAD

**Issue by ilyar** [bem-site/bem-lib-site-view#11]
Предложение индекс документации это список блоков дополненный информацией из корневого `readme.md` это может быть опциональным поведением.

**Comment by tadatuta** [comment]
Да, так и планировалось. Задача в работе у @vithar.

**Comment by vithar** [comment]
Список блоков всегда будет справа, а слева на корневой странице будет readme.(lang.)md

**Comment by ilyar** [comment]
не уверен, что верно понял:
- index: [list][readme.md] - не видел еще этой страницы, но полагаю список тоже должен быть слева;
- block: [list][block.md] - сейчас генерится именно так так список слева.

**Comment by vithar** [comment]
Готово. Будет окончательно готово после закрытия этого PR: https://github.com/bem-site/bem-lib-site-view/pull/21

**Comment by ilyar** [comment]
@vithar не работает, тестировал на свежем коде https://github.com/bem-site/bem-lib-site-data/commit/3924f69334ceec0f4eb8a1d0f533dcf9c17608a8 и https://github.com/ilyar/bem-lib-site-view/commit/9bbac76d38791d020b16f1afe90ba9240a640fcd (https://github.com/bem-site/bem-lib-site-view/commit/47ad89ec840f9d615a35af2cd31544c3153d305c) индекс не создается:

``` bash
tree distr/docs/
distr/docs/
├── data
│   └── docstest
│       ├── bower.json
│       ├── data.json
│       ├── desktop.docs
│       │   └── b1
│       │       ├── b1.bemdecl.js
│       │       ├── b1.data.json
│       │       ├── b1.jsdoc.html
│       │       ├── b1.jsdoc.json
│       │       ├── b1.jsdoc.md
│       │       ├── b1.meta.json
│       │       ├── b1.ru.doc.html
│       │       ├── b1.ru.md
│       │       └── b1.source-files.json
│       └── readme.md
└── docstest
    └── ru
        ├── desktop
        │   └── b1
        │       └── index.html
        ├── favicon.ico
        ├── index.css
        └── index.js
```

**Comment by vithar** [comment]
Так а view у тебя свежий?

**Comment by ilyar** [comment]
Да свежий.

**Comment by vithar** [comment]
Дай ссылку на репозиторий с библиотекой, проверю на чистой установке.

**Comment by ilyar** [comment]
Использую как описано тут
https://github.com/bem-site/bem-lib-site-view/issues/12 ссылка на форк
выше. Вечером опубликую проект, но там ничего особенного.

**Comment by ilyar** [comment]
Фактически это bem-lib-site со свежими data и view.

**Comment by vithar** [comment]
Я не публиковал свежие data и view в npm, если склонировать, сделать npm i, а потом запускать — у меня всё работает.

**Comment by ilyar** [comment]
Т.е если я склонирую bem-lib-sit заменю data и view на мастер с гитхаба то
всё будет работать. Я правильно понял?

**Comment by vithar** [comment]
Да.

**Comment by ilyar** [comment]
@vithar что я делаю не так? наверное я не правильно тебя понял.

Клонирую bem-lib-sit заменю data и view на мастер с гитхаба:

``` bash
git clone git@github.com:bem-site/bem-lib-site.git
cd bem-lib-site
npm i -S bem-site/bem-lib-site-data
npm i -S bem-site/bem-lib-site-view
./bin/bem-lib-site .
module.js:341
    throw err;
    ^

Error: Cannot find module '/space/projects/gendocs/bem-lib-site/node_modules/bem-lib-site-view/desktop.bundles/index/index.bemtree'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/space/projects/gendocs/bem-lib-site/node_modules/bem-lib-site-view/index.js:13:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Получаю ошибку описанную в #12.

**Comment by vithar** [comment]
Я не использую bem-lib-site, а клонирую рядом bem-lib-site-view и bem-lib-site-data, делаю в них npm i, а потом запускаю последовательно bem-lib-site-data/bin/bem-lib-site-data и bem-lib-site-view/bin/bem-lib-site-view

**Comment by ilyar** [comment]
@vithar [сделал как ты написал](https://github.com/ilyar/bem-lib-site-test/blob/master/package.json#L11) индекс создается, но `Markdown` на не конвертируется в `html` (https://ilyar.github.io/bem-lib-site-test/):

``` bash
git clone git@github.com:ilyar/bem-lib-site-test.git
cd bem-lib-site-test && npm install
npm test
```

Наверное это новый issue?

**Comment by vithar** [comment]
Это еще не сделали.

**Comment by ilyar** [comment]
понял, спасибо.
